// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OrderEquipamentController from "./order_equipament_controller"
application.register("order-equipament", OrderEquipamentController)

import SidenavToggleController from "./sidenav_toggle_controller"
application.register("sidenav-toggle", SidenavToggleController)

import ThemeToggleController from "./theme_toggle_controller"
application.register("theme-toggle", ThemeToggleController)

import UpdateOrderSelectController from "./update_order_select_controller"
application.register("update-order-select", UpdateOrderSelectController)
